// <auto-generated />
namespace Shop1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addedOrderAndProductCount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedOrderAndProductCount));
        
        string IMigrationMetadata.Id
        {
            get { return "201406221238288_addedOrderAndProductCount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
